// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzElXFsBwsf8cPax7L_nxOrLOshCzArnM',
    appId: '1:989443742859:web:aef6a392b080ca50eac88e',
    messagingSenderId: '989443742859',
    projectId: 'access-hub-f5fc4',
    authDomain: 'access-hub-f5fc4.firebaseapp.com',
    storageBucket: 'access-hub-f5fc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4l3S4a7M5J4OiBa8q60Zi1dXb7D0W4-A',
    appId: '1:989443742859:android:bddb10175f1ed318eac88e',
    messagingSenderId: '989443742859',
    projectId: 'access-hub-f5fc4',
    storageBucket: 'access-hub-f5fc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnei8DU3w0SytOzMEWORP9HphhpAB2dwc',
    appId: '1:989443742859:ios:3119525a0771daa9eac88e',
    messagingSenderId: '989443742859',
    projectId: 'access-hub-f5fc4',
    storageBucket: 'access-hub-f5fc4.firebasestorage.app',
    iosBundleId: 'com.example.accessHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnei8DU3w0SytOzMEWORP9HphhpAB2dwc',
    appId: '1:989443742859:ios:3119525a0771daa9eac88e',
    messagingSenderId: '989443742859',
    projectId: 'access-hub-f5fc4',
    storageBucket: 'access-hub-f5fc4.firebasestorage.app',
    iosBundleId: 'com.example.accessHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzElXFsBwsf8cPax7L_nxOrLOshCzArnM',
    appId: '1:989443742859:web:64d993e57dbaca10eac88e',
    messagingSenderId: '989443742859',
    projectId: 'access-hub-f5fc4',
    authDomain: 'access-hub-f5fc4.firebaseapp.com',
    storageBucket: 'access-hub-f5fc4.firebasestorage.app',
  );
}
